<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="index.php?c=topic&create=1" method="POST">
        <input type="text" name="title" placeholder="Título" required>
        <textarea name="description">
        </textarea>
        <input type="submit" name="addPost" value="Crear tema">
    </form>
    <a href="index.php">Volver</a>
</body>

</html>