<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="public/style.css">
</head>
<body>
    LOGIN
    <form action="index.php?c=user" method="POST">
        <input type="text" name="username" placeholder="nombre de usuario">
        <input type="password" name="password" placeholder="contraseña">
        <input type="submit" value="Entrar">
</form>

<p>¿No tienes cuenta? <a href="index.php?c=user&register=1">Registrarse</a></p>

</body>
</html>