<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
</head>

<body>
    <h1>Perfil</h1>
    <?php
    if ($_SESSION['user']) {
    ?>
        <h3>Nombre: <?php echo $_SESSION['user']->getUsername(); ?></h3>
        <?php if ($_SESSION['user']->getAvatar()) { ?>
            <img src="public/img/<?php echo $_SESSION['user']->getAvatar(); ?>" alt="avatar" style="max-width:150px;max-height:150px;border-radius: 50%;" />
        <?php } ?>
        <h3>Rol: <?php if ($_SESSION['user']->getRol()) {
                    ?>
                Admin
            <?php
                    } else {
            ?>
                Usuario
            <?php
                    } ?></h3>
    <?php
    }
    ?>

    <a href="index.php">Volver</a>
</body>

</html>