<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="public/style.css">
</head>

<body>
    <?php
    if (!$topic) {
        echo "<script>alert('INCORRECTO')</script>";
    } else {
        echo "<h1>" . $topic->getTitle() . "</h1>";
        echo $topic->getDescription() . "<br>";
        echo "Escrito por: <strong>" . $topic->getIdAuthor()->getUsername() . "</strong>  el <strong>" . $topic->getDate() . "</strong><br>";
        echo "<br>";

    ?>
        <form method="POST" action="index.php?c=comment&id=<?php echo $_GET['id']; ?>">
            <textarea name="content"></textarea>

            <input type="submit" value="Enviar comentario" name="addComment">
        </form><br>
        <a href="index.php">Volver</a><br>
    <?php
        echo "COMENTARIOS: <br><br>";

        foreach ($comments as $comment) {
            if ($_SESSION["user"]->getRol() || $comment->getIdAuthor()->getId() == $_SESSION["user"]->getId()) {
                echo "<a href='index.php?c=comment&delete=" . $comment->getId() . "&post_id=" . $topic->getId() . "'>X</a> ";
            }
            echo $comment->getDate() . " - <strong>" . $comment->getIdAuthor()->getUsername() . "</strong>: " . $comment->getContent() . "<br>";
        }
    }

    ?>

</body>

</html>